version: '3'
services:
  dev:
    image: node:lts
    volumes:
      - nodemodules:/usr/src/service/node_modules
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: yarn start
    ports:
      - 4000:4000

volumes:
  nodemodules:
    external: true
