version: '2'
services:
  base:
    image: node:lts
    volumes:
      - nodemodules:/usr/src/service/node_modules
      - .:/usr/src/service/
    working_dir: /usr/src/service/
  install:
    extends:
      service: base
    command: yarn
  build:
    extends:
      service: base
    command: yarn build
  create-bundles:
    extends:
      service: base
    command: yarn run create-bundles

volumes:
  nodemodules:
    external: true
